[build]
  # Directory where the React app is located
  base = "frontend"
  
  # Command to build the React app
  command = "yarn install && yarn build"
  
  # Directory to publish (relative to base directory)
  publish = "build"

[build.environment]
  # Node version
  NODE_VERSION = "20"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
